color0 #1e100d
color1 #ffb4ab
color2 #ffb4a7
color3 #ffb4a7
color4 #ffb94e
color5 #ffb4a7
color6 #ffb4a7
color7 #f9dcd7
color8 #ab8983
color9 #ffb4ab
color10 #ffb4a7
color11 #ffb4a7
color12 #ffb94e
color13 #ffb4a7
color14 #ffb4a7
color15 #f9dcd7

cursor                #f9dcd7
cursor_text_color     #1e100d
background            #1e100d
foreground            #f9dcd7
selection_foreground  #e4beb7
selection_background  #5b403b
active_border_color   #ffb4a7
inactive_border_color #5b403b
url_color             #ffb4a7

active_tab_foreground   #670500
active_tab_background   #ffb4a7
inactive_tab_foreground #e4beb7
inactive_tab_background #5b403b
cursor_trail_color      #e4beb7
